services:
  php:
    image: php:8.2-fpm-alpine
    container_name: submonitor-php
    user: root
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./rules:/etc/nginx/rules
      - ./rules:/var/www/html/rules
      - ./ssl:/etc/nginx/ssl
      - log-data:/var/log/nginx

  nginx:
    image: nginx:alpine
    container_name: submonitor-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./rules:/etc/nginx/rules
      - ./ssl:/etc/nginx/ssl
      - ./entrypoint.sh:/entrypoint.sh
      - log-data:/var/log/nginx
    depends_on:
      - php
    entrypoint: [
      "sh", "-c",
      "chmod +x /entrypoint.sh && chmod -R 777 /var/www/html /etc/nginx/conf.d /etc/nginx/rules /etc/nginx/ssl && /entrypoint.sh"
    ]

volumes:
  log-data:
