version: '3.8'

services:
  php:
    image: php:8.2-fpm-alpine
    container_name: submonitor-php
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./rules:/etc/nginx/rules
      - log-data:/var/log/nginx

  nginx:
    image: nginx:alpine
    container_name: submonitor-nginx
    restart: always
    ports:
      - "80:80"     # HTTP 端口
      - "443:443"   # HTTPS 加密端口
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./rules:/etc/nginx/rules
      - ./ssl:/etc/nginx/ssl
      - log-data:/var/log/nginx
    depends_on:
      - php
    command: >
      /bin/sh -c "
      (while true; do
        if [ -f /etc/nginx/rules/.reload_flag ]; then
          rm -f /etc/nginx/rules/.reload_flag
          nginx -s reload
        fi
        sleep 2
      done) &
      exec nginx -g 'daemon off;'
      "

volumes:
  log-data:
